apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCSAgImF1dGgiOiAiWVhWemMybGxiV0Z1T21kb2NGOUJVVWxvY0Zkd09IbFFjSEZzZFZsTllsbFlOMjlYUldGWVJHNVBlVEV4VTNRMU9WTT0iCgkJfQoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
